[build]
    command = "npm run build"  # Adjust this if needed
    functions = "functions"    # Folder containing your serverless functions
    publish = ""

[dev]
    functions = "functions"    # Folder containing your serverless functions
    publish = ""
