[build]
command = "npm run build"  # Adjust this if needed
functions = "functions"    # Folder containing your serverless functions

[dev]
functions = "functions"    # Folder containing your serverless functions